### ISSUE TITLE
netlify deployment failing 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [janosh/janosh.io#61]
Hi, I was wondering if you can help me with this. I was building a ML research website for my own startup & this was a great beginning point to start with. It had everything that I was looking for  
* Way to integrate JS code(MDX) ...to show tweak paper code on the blog itself ...add buttons...sliders etc
* a labelled Blog
* Algolia search to search content 
* Github project showcase
* a starter theme (which I will change once I have a UI developer...I'm looking for something minimal and fun) 

Also I'm new to GraphQL, Gatsby & Netlify so I can't really do much right now. Thanks for a great project  :) 

```
7:46:15 AM: Build ready to start
7:46:17 AM: build-image version: 9cade8af58c2cf3a17a1e9433d2e979149488837
7:46:17 AM: build-image tag: v3.3.5
7:46:17 AM: buildbot version: 6067c60f3bc043bb6b9ee9b57c85b10029c65bfd
7:46:17 AM: Fetching cached dependencies
7:46:18 AM: Failed to fetch cache, continuing with build
7:46:18 AM: Starting to prepare the repo for build
7:46:18 AM: No cached dependencies found. Cloning fresh repo
7:46:18 AM: git clone git@gitlab.com:flickscapital/janosh.io
7:46:19 AM: Preparing Git Reference refs/heads/master
7:46:20 AM: Found Netlify configuration file netlify.toml in site root
7:46:20 AM: Found Netlify configuration file(s). Overriding site configuration
7:46:20 AM: No build command found, continuing to publishing
7:46:20 AM: failed during stage 'building site': Deploy directory 'public' does not exist
7:46:20 AM: Failing build: Failed to build site
```

I saw .netlify config file & it had mentioned 

```
[build]
  publish = "public"
```

which seems correct what's wrong?

**Comment by janosh** [comment]
The problem is that Netlify can't infer your build command which is odd. Usually they recognize Gatsby repos. In any case, you can specify a command manually by adding the following line to your `netlify.toml` under the `[build]` section:

```toml
command = "gatsby build"
```

[See here for more details](https://docs.netlify.com/configure-builds/file-based-configuration). Let me know if that helps.

Also, you can just delete the `.netlify` directory as it only contains my site ID. Yours will be different. Maybe that's even the cause of the problem.

**Comment by AbhimanyuAryan** [comment]
@janosh thanks will try

**Comment by janosh** [comment]
Haven't heard back so I'll close this issue for now. Feel free to reopen if you're still having difficulties.
